package com.aftersales.copilot.ticket.domain;
public enum TicketStatus { SUBMITTED, PENDING_ASSIGNMENT, PENDING_AGENT, PENDING_CUSTOMER, WAITING_RETURN, RETURN_IN_TRANSIT, RETURN_RECEIVED, PROCESSING, RESOLVED, REJECTED, CANCELLED, CLOSED }
