CREATE TABLE service_proposal (
    id BIGINT UNSIGNED NOT NULL,
    proposal_no VARCHAR(32) NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    type VARCHAR(24) NOT NULL,
    source VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    requested_amount_cent BIGINT NOT NULL DEFAULT 0,
    refund_amount_cent BIGINT NOT NULL DEFAULT 0,
    reason_code VARCHAR(40) NULL,
    description TEXT NOT NULL,
    conditions_json JSON NULL,
    created_by BIGINT UNSIGNED NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    expires_at DATETIME(3) NOT NULL,
    confirmed_at DATETIME(3) NULL,
    rejected_at DATETIME(3) NULL,
    executed_at DATETIME(3) NULL,
    version INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_proposal_no UNIQUE (proposal_no),
    INDEX idx_proposal_ticket_created(ticket_id, created_at),
    INDEX idx_proposal_ticket_status(ticket_id, status),
    CONSTRAINT fk_proposal_ticket FOREIGN KEY (ticket_id) REFERENCES service_ticket(id),
    CONSTRAINT fk_proposal_creator FOREIGN KEY (created_by) REFERENCES sys_user(id),
    CONSTRAINT fk_proposal_reviewer FOREIGN KEY (reviewed_by) REFERENCES sys_user(id),
    CONSTRAINT chk_proposal_type CHECK (type IN ('REFUND_ONLY','RETURN_REFUND','EXCHANGE','REPAIR')),
    CONSTRAINT chk_proposal_source CHECK (source IN ('AI','AGENT')),
    CONSTRAINT chk_proposal_status CHECK (status IN ('DRAFT','PENDING_CONFIRMATION','CONFIRMED','REJECTED','EXPIRED','EXECUTED','FAILED')),
    CONSTRAINT chk_proposal_amount CHECK (requested_amount_cent >= 0 AND refund_amount_cent >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE proposal_execution (
    id BIGINT UNSIGNED NOT NULL,
    proposal_id BIGINT UNSIGNED NOT NULL,
    idempotency_key VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    executor_id BIGINT UNSIGNED NOT NULL,
    request_hash CHAR(64) NOT NULL,
    result_json JSON NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_proposal_execution_proposal UNIQUE (proposal_id),
    CONSTRAINT uk_proposal_execution_key UNIQUE (idempotency_key),
    CONSTRAINT fk_execution_proposal FOREIGN KEY (proposal_id) REFERENCES service_proposal(id),
    CONSTRAINT fk_execution_executor FOREIGN KEY (executor_id) REFERENCES sys_user(id),
    CONSTRAINT chk_execution_status CHECK (status IN ('PROCESSING','SUCCEEDED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE refund_record (
    id BIGINT UNSIGNED NOT NULL,
    refund_no VARCHAR(32) NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    proposal_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NOT NULL,
    amount_cent BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_refund_no UNIQUE (refund_no),
    CONSTRAINT uk_refund_proposal UNIQUE (proposal_id),
    CONSTRAINT fk_refund_ticket FOREIGN KEY (ticket_id) REFERENCES service_ticket(id),
    CONSTRAINT fk_refund_proposal FOREIGN KEY (proposal_id) REFERENCES service_proposal(id),
    CONSTRAINT fk_refund_item FOREIGN KEY (order_item_id) REFERENCES order_item(id),
    CONSTRAINT chk_refund_status CHECK (status IN ('PROCESSING','SUCCEEDED','FAILED')),
    CONSTRAINT chk_refund_amount CHECK (amount_cent > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE audit_log (
    id BIGINT UNSIGNED NOT NULL,
    trace_id VARCHAR(64) NULL,
    actor_type VARCHAR(20) NOT NULL,
    actor_id BIGINT UNSIGNED NULL,
    action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    resource_id BIGINT UNSIGNED NULL,
    result VARCHAR(20) NOT NULL,
    ip VARCHAR(64) NULL,
    user_agent VARCHAR(255) NULL,
    before_json JSON NULL,
    after_json JSON NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    INDEX idx_audit_resource_time(resource_type, resource_id, created_at),
    INDEX idx_audit_actor_time(actor_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
