CREATE TABLE return_order (
    id BIGINT UNSIGNED NOT NULL,
    return_no VARCHAR(32) NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    proposal_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL,
    return_address_snapshot JSON NULL,
    carrier_code VARCHAR(32) NULL,
    tracking_no VARCHAR(64) NULL,
    shipped_at DATETIME(3) NULL,
    received_at DATETIME(3) NULL,
    inspected_at DATETIME(3) NULL,
    inspection_result VARCHAR(24) NULL,
    inspection_note VARCHAR(1000) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_return_no UNIQUE (return_no),
    CONSTRAINT uk_return_proposal UNIQUE (proposal_id),
    CONSTRAINT fk_return_ticket FOREIGN KEY (ticket_id) REFERENCES service_ticket(id),
    CONSTRAINT fk_return_proposal FOREIGN KEY (proposal_id) REFERENCES service_proposal(id),
    CONSTRAINT fk_return_item FOREIGN KEY (order_item_id) REFERENCES order_item(id),
    CONSTRAINT chk_return_status CHECK (status IN ('WAITING_SHIPMENT','IN_TRANSIT','RECEIVED','INSPECTED','CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE exchange_order (
    id BIGINT UNSIGNED NOT NULL,
    exchange_no VARCHAR(32) NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    proposal_id BIGINT UNSIGNED NOT NULL,
    return_order_id BIGINT UNSIGNED NOT NULL,
    replacement_sku_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL,
    replacement_shipment_id BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_exchange_no UNIQUE (exchange_no),
    CONSTRAINT uk_exchange_proposal UNIQUE (proposal_id),
    CONSTRAINT fk_exchange_ticket FOREIGN KEY (ticket_id) REFERENCES service_ticket(id),
    CONSTRAINT fk_exchange_proposal FOREIGN KEY (proposal_id) REFERENCES service_proposal(id),
    CONSTRAINT fk_exchange_return FOREIGN KEY (return_order_id) REFERENCES return_order(id),
    CONSTRAINT fk_exchange_sku FOREIGN KEY (replacement_sku_id) REFERENCES product_sku(id),
    CONSTRAINT fk_exchange_shipment FOREIGN KEY (replacement_shipment_id) REFERENCES logistics_shipment(id),
    CONSTRAINT chk_exchange_status CHECK (status IN ('WAITING_RETURN','PROCESSING','SHIPPED','COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE repair_order (
    id BIGINT UNSIGNED NOT NULL,
    repair_no VARCHAR(32) NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    proposal_id BIGINT UNSIGNED NOT NULL,
    return_order_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(24) NOT NULL,
    fault_conclusion VARCHAR(1000) NULL,
    repair_note VARCHAR(2000) NULL,
    repair_return_shipment_id BIGINT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_repair_no UNIQUE (repair_no),
    CONSTRAINT uk_repair_proposal UNIQUE (proposal_id),
    CONSTRAINT fk_repair_ticket FOREIGN KEY (ticket_id) REFERENCES service_ticket(id),
    CONSTRAINT fk_repair_proposal FOREIGN KEY (proposal_id) REFERENCES service_proposal(id),
    CONSTRAINT fk_repair_return FOREIGN KEY (return_order_id) REFERENCES return_order(id),
    CONSTRAINT fk_repair_shipment FOREIGN KEY (repair_return_shipment_id) REFERENCES logistics_shipment(id),
    CONSTRAINT chk_repair_status CHECK (status IN ('WAITING_RECEIPT','INSPECTING','REPAIRING','SHIPPED_BACK','COMPLETED','FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
