CREATE TABLE ai_task (
    id BIGINT UNSIGNED NOT NULL,
    biz_type VARCHAR(32) NOT NULL,
    biz_id BIGINT UNSIGNED NOT NULL,
    dedup_key VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    request_snapshot JSON NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    started_at DATETIME(3) NULL,
    finished_at DATETIME(3) NULL,
    next_retry_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_task_dedup (dedup_key),
    KEY idx_ai_task_status_retry (status,next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE ai_analysis (
    id BIGINT UNSIGNED NOT NULL,
    ticket_id BIGINT UNSIGNED NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    ticket_version INT NOT NULL,
    intent VARCHAR(32) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    priority_suggestion VARCHAR(16) NOT NULL,
    sentiment VARCHAR(24) NOT NULL,
    extracted_json JSON NULL,
    missing_fields_json JSON NULL,
    reply_suggestion MEDIUMTEXT NULL,
    proposal_suggestion_json JSON NULL,
    needs_human TINYINT(1) NOT NULL,
    risk_flags_json JSON NULL,
    citations_json JSON NULL,
    provider VARCHAR(64) NULL,
    model VARCHAR(128) NULL,
    prompt_version VARCHAR(64) NULL,
    input_tokens INT NULL,
    output_tokens INT NULL,
    estimated_cost_micros BIGINT NULL,
    latency_ms BIGINT NULL,
    stale TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ai_analysis_task (task_id),
    KEY idx_ai_analysis_ticket (ticket_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE outbox_event (
    event_id VARCHAR(36) NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    routing_key VARCHAR(128) NOT NULL,
    payload JSON NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME(3) NULL,
    published_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (event_id),
    KEY idx_outbox_publish (status,next_retry_at,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
