package com.aftersales.copilot.aiadapter.application;

import com.aftersales.copilot.aiadapter.provider.ChatProvider;
import com.aftersales.copilot.common.ai.AiTaskScheduler; import com.aftersales.copilot.common.ai.AiTaskRetryService;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime; import java.time.ZoneOffset; import java.util.*;

@Service
public class AiTaskApplicationService implements AiTaskScheduler, AiTaskRetryService {
    private final JdbcTemplate jdbc; private final ObjectMapper json; private final ChatProvider provider;
    public AiTaskApplicationService(JdbcTemplate jdbc,ObjectMapper json,ChatProvider provider){this.jdbc=jdbc;this.json=json;this.provider=provider;}
    @Override @Transactional
    public void scheduleTicketAnalysis(long ticketId,int ticketVersion,long customerId){
        long taskId = Math.abs(UUID.randomUUID().getMostSignificantBits()); String dedup="TICKET_ANALYSIS:"+ticketId+":"+ticketVersion; LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);
        String snapshot="{\"ticketId\":"+ticketId+",\"ticketVersion\":"+ticketVersion+",\"customerId\":"+customerId+"}";
        try { jdbc.update("INSERT INTO ai_task(id,biz_type,biz_id,dedup_key,status,attempt_count,max_attempts,request_snapshot,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",taskId,"TICKET_ANALYSIS",ticketId,dedup,"PENDING",0,3,snapshot,now,now); }
        catch(Exception e){ return; }
        Map<String,Object> envelope=new LinkedHashMap<>(); envelope.put("eventId",UUID.randomUUID().toString()); envelope.put("eventType","ticket.ai.analyze.requested.v1"); envelope.put("occurredAt",now.toString()); envelope.put("traceId",UUID.randomUUID().toString()); envelope.put("producer","aftersales-server"); envelope.put("schemaVersion",1); envelope.put("data",Map.of("taskId",taskId,"ticketId",ticketId,"ticketVersion",ticketVersion,"customerId",customerId));
        try { jdbc.update("INSERT INTO outbox_event(event_id,aggregate_type,aggregate_id,event_type,routing_key,payload,status,retry_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,0,?,?)",envelope.get("eventId"),"AI_TASK",taskId,"ticket.ai.analyze.requested.v1","ticket.ai.analyze.requested.v1",json.writeValueAsString(envelope),"NEW",now,now); } catch(Exception e){throw new IllegalStateException(e);}
    }
    @Transactional public Map<String,Object> callback(Map<String,Object> payload) throws Exception {
        long taskId=((Number)payload.get("taskId")).longValue(); String status=String.valueOf(payload.getOrDefault("status","FAILED")); LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);
        if("SUCCEEDED".equals(status)){
            Map<String,Object> result=(Map<String,Object>)payload.getOrDefault("result",Map.of()); long ticketId=((Number)payload.get("ticketId")).longValue(); int version=((Number)payload.getOrDefault("ticketVersion",0)).intValue();
            boolean stale=jdbc.queryForObject("SELECT version<>? FROM service_ticket WHERE id=?",Boolean.class,version,ticketId);
            Map<String,Object> usage=(Map<String,Object>)payload.getOrDefault("usage",new HashMap<>());
            jdbc.update("INSERT IGNORE INTO ai_analysis(id,ticket_id,task_id,ticket_version,intent,confidence,priority_suggestion,sentiment,extracted_json,missing_fields_json,reply_suggestion,proposal_suggestion_json,needs_human,risk_flags_json,citations_json,provider,model,prompt_version,input_tokens,output_tokens,estimated_cost_micros,latency_ms,stale,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",Math.abs(UUID.randomUUID().getMostSignificantBits()),ticketId,taskId,version,String.valueOf(result.getOrDefault("intent","OTHER")),Double.parseDouble(String.valueOf(result.getOrDefault("confidence",0))),String.valueOf(result.getOrDefault("prioritySuggestion","MEDIUM")),String.valueOf(result.getOrDefault("sentiment","NEUTRAL")),json.writeValueAsString(result.get("extracted")),json.writeValueAsString(result.get("missingFields")),result.get("replySuggestion"),json.writeValueAsString(result.get("proposalSuggestion")),Boolean.TRUE.equals(result.get("needsHuman")),json.writeValueAsString(result.get("riskFlags")),json.writeValueAsString(result.get("citations")),String.valueOf(usage.getOrDefault("provider","unknown")),String.valueOf(usage.getOrDefault("model","unknown")),String.valueOf(usage.getOrDefault("promptVersion","ticket-analysis-v1")),0,0,0,0,stale,now);
            createAiDraftIfSafe(ticketId,result,stale,now);
            jdbc.update("UPDATE ai_task SET status='SUCCEEDED',finished_at=?,updated_at=? WHERE id=? AND status<>'SUCCEEDED'",now,now,taskId);
        } else jdbc.update("UPDATE ai_task SET status='FAILED',error_code=?,error_message=?,finished_at=?,next_retry_at=?,updated_at=? WHERE id=? AND status<>'SUCCEEDED'",payload.getOrDefault("errorCode","AI_FAILED"),payload.getOrDefault("errorMessage","analysis failed"),now,now.plusSeconds(30),now,taskId);
        return Map.of("accepted",true);
    }
    private void createAiDraftIfSafe(long ticketId,Map<String,Object> result,boolean stale,LocalDateTime now)throws Exception{if(stale||Boolean.TRUE.equals(result.get("needsHuman"))||result.get("proposalSuggestion")==null)return;if(jdbc.queryForObject("SELECT COUNT(*) FROM service_proposal WHERE ticket_id=? AND status IN ('DRAFT','PENDING_CONFIRMATION','CONFIRMED')",Integer.class,ticketId)>0)return;Map<String,Object> s=(Map<String,Object>)result.get("proposalSuggestion");String type=String.valueOf(s.getOrDefault("type",result.getOrDefault("intent","OTHER")));if(!Set.of("REFUND_ONLY","RETURN_REFUND","EXCHANGE","REPAIR").contains(type))return;long id=Math.abs(UUID.randomUUID().getMostSignificantBits());String no="SP"+now.toLocalDate().toString().replace("-","")+String.format("%06d",Math.floorMod(id,1000000));long amount=type.equals("REFUND_ONLY")&&s.get("suggestedRefundAmountCent") instanceof Number n?n.longValue():0;String conditions=json.writeValueAsString(s.getOrDefault("conditions",Collections.emptyMap()));Object reason=s.get("reasonCode");jdbc.update("INSERT INTO service_proposal(id,proposal_no,ticket_id,type,source,status,requested_amount_cent,refund_amount_cent,reason_code,description,conditions_json,created_by,expires_at,version,created_at,updated_at) VALUES(?,?,?,?,?,'DRAFT',?,?,?,?,?,NULL,?,0,?,?)",id,no,ticketId,type,"AI",amount,amount,reason,String.valueOf(s.getOrDefault("description","AI 建议售后方案，待客服审核")),conditions,now.plusHours(24),now,now);}
    @Override public Object latestAnalysis(long ticketId){return jdbc.queryForList("SELECT * FROM ai_analysis WHERE ticket_id=? ORDER BY created_at DESC LIMIT 1",ticketId).stream().findFirst().orElse(Map.of("status","NOT_FOUND"));}
    @Override @Transactional public Object retryTicketAnalysis(long ticketId,long operatorId){Map<String,Object> t=jdbc.queryForList("SELECT * FROM ai_task WHERE biz_type='TICKET_ANALYSIS' AND biz_id=? ORDER BY created_at DESC LIMIT 1",ticketId).stream().findFirst().orElseThrow();int attempts=((Number)t.getOrDefault("attempt_count",0)).intValue(),max=((Number)t.getOrDefault("max_attempts",3)).intValue();if(attempts>=max)throw new IllegalStateException("AI_TASK_MAX_ATTEMPTS");long taskId=((Number)t.get("id")).longValue();LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);int version=jdbc.queryForObject("SELECT version FROM service_ticket WHERE id=?",Integer.class,ticketId);jdbc.update("UPDATE ai_task SET status='PENDING',attempt_count=attempt_count+1,error_code=NULL,error_message=NULL,next_retry_at=NULL,updated_at=? WHERE id=?",now,taskId);Map<String,Object> env=new LinkedHashMap<>();env.put("eventId",UUID.randomUUID().toString());env.put("eventType","ticket.ai.analyze.requested.v1");env.put("occurredAt",now.toString());env.put("traceId",UUID.randomUUID().toString());env.put("producer","aftersales-server");env.put("schemaVersion",1);env.put("data",Map.of("taskId",taskId,"ticketId",ticketId,"ticketVersion",version));try{jdbc.update("INSERT INTO outbox_event(event_id,aggregate_type,aggregate_id,event_type,routing_key,payload,status,retry_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,0,?,?)",env.get("eventId"),"AI_TASK",taskId,env.get("eventType"),env.get("eventType"),json.writeValueAsString(env),"NEW",now,now);}catch(Exception e){throw new IllegalStateException(e);}return Map.of("taskId",taskId,"status","PENDING","attemptCount",attempts+1);}
    @Transactional public Map<String,Object> documentCallback(Map<String,Object> payload) throws Exception {
        long documentId=((Number)payload.get("documentId")).longValue(); String status=String.valueOf(payload.getOrDefault("status","FAILED")); LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);
        if("SUCCEEDED".equals(status)) { var chunks=(List<Map<String,Object>>)payload.getOrDefault("chunks",List.of()); jdbc.update("UPDATE knowledge_document SET status='INDEXED',chunk_count=?,updated_at=? WHERE id=?",chunks.size(),now,documentId); for(var c:chunks) jdbc.update("INSERT IGNORE INTO knowledge_chunk_meta(id,document_id,chunk_id,index_version,sequence_no,section_title,content_hash,token_count,qdrant_point_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)",Math.abs(UUID.randomUUID().getMostSignificantBits()),documentId,c.get("chunkId"),payload.getOrDefault("indexVersion",1),c.getOrDefault("sequenceNo",0),c.get("sectionTitle"),c.get("contentHash"),0,c.get("qdrantPointId"),now); }
        else jdbc.update("UPDATE knowledge_document SET status='FAILED',error_message=?,updated_at=? WHERE id=?",payload.getOrDefault("errorMessage","index failed"),now,documentId);
        return Map.of("accepted",true);
    }
}
