package com.aftersales.copilot.aiadapter.api;
import com.aftersales.copilot.auth.domain.AuthenticatedUser; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.reactive.function.client.WebClient; import reactor.core.publisher.Flux; import java.util.*;
@RestController @RequestMapping("/api/v1/tickets") public class AiChatProxyController {
 private final WebClient client; private final ObjectMapper mapper; private final String secret;
 private final com.aftersales.copilot.auth.application.TicketAccessGuard access;
 public AiChatProxyController(WebClient.Builder b,ObjectMapper m,@Value("${app.ai.base-url}") String base,@Value("${app.ai.java-internal-secret}") String secret,com.aftersales.copilot.auth.application.TicketAccessGuard access){client=b.baseUrl(base).build();mapper=m;this.secret=secret;this.access=access;}
 @PostMapping(value="/{ticketId}/ai-chat/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) public Flux<String> stream(@AuthenticationPrincipal AuthenticatedUser user,@PathVariable long ticketId,@jakarta.validation.Valid @RequestBody ChatMessage body){access.requireAccess(user,ticketId); try{Map<String,Object> payload=Map.of("ticketId",ticketId,"message",body.message());String json=mapper.writeValueAsString(payload);String nonce=UUID.randomUUID().toString();long timestamp=System.currentTimeMillis();return client.post().uri("/internal/v1/chat/stream").contentType(MediaType.APPLICATION_JSON).header("X-Internal-Service","aftersales-server").header("X-Internal-Timestamp",String.valueOf(timestamp)).header("X-Internal-Nonce",nonce).header("X-Internal-Signature",com.aftersales.copilot.common.security.HmacSignature.sign(secret,timestamp,nonce,"POST","/internal/v1/chat/stream",json)).bodyValue(json).retrieve().bodyToFlux(String.class);}catch(Exception e){return Flux.error(e);}}
 public record ChatMessage(@jakarta.validation.constraints.NotBlank @jakarta.validation.constraints.Size(max=4000) String message){}
}
