package com.aftersales.copilot.ticket.infrastructure.mapper;
import com.aftersales.copilot.ticket.infrastructure.po.*; import com.baomidou.mybatisplus.core.mapper.BaseMapper; import org.apache.ibatis.annotations.*; import java.time.LocalDateTime; import java.util.*;
@Mapper public interface TicketMapper extends BaseMapper<ServiceTicketPo> {
 record OrderContext(Long itemId,Long orderId,Long customerId,String orderStatus,String productName) {}
 record TicketView(Long id,String ticketNo,Long customerId,Long orderId,Long orderItemId,String requestedType,String confirmedType,String status,String priority,String title,String description,Long assignedAgentId,LocalDateTime firstResponseAt,LocalDateTime resolvedAt,LocalDateTime closedAt,String resolutionCode,String resolutionNote,Integer version,LocalDateTime createdAt,LocalDateTime updatedAt) {}
 record MessageView(Long id,String senderType,Long senderId,String visibility,String messageType,String content,LocalDateTime createdAt) {}
 record TimelineView(Long id,String eventType,String actorType,Long actorId,String summary,String detailJson,LocalDateTime createdAt) {}
 @Select("SELECT oi.id itemId, co.id orderId, co.customer_id customerId, co.status orderStatus, oi.product_name_snapshot productName FROM order_item oi JOIN customer_order co ON co.id=oi.order_id WHERE oi.id=#{itemId} AND co.customer_id=#{customerId} LIMIT 1") Optional<OrderContext> findOrderItemForCustomer(@Param("itemId") long itemId,@Param("customerId") long customerId);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket WHERE id=#{id}") Optional<TicketView> findView(@Param("id") long id);
 @Select("SELECT id FROM service_ticket WHERE customer_id=#{customerId} AND client_request_id=#{clientRequestId} LIMIT 1") Optional<Long> findByClientRequest(@Param("customerId") long customerId,@Param("clientRequestId") String clientRequestId);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket WHERE customer_id=#{userId} ORDER BY created_at DESC LIMIT #{limit} OFFSET #{offset}") List<TicketView> listCustomer(@Param("userId") long userId,@Param("limit") int limit,@Param("offset") int offset);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket WHERE (assigned_agent_id=#{userId} OR (#{queue}=1 AND status='PENDING_ASSIGNMENT')) ORDER BY created_at DESC LIMIT #{limit} OFFSET #{offset}") List<TicketView> listAgent(@Param("userId") long userId,@Param("queue") int queue,@Param("limit") int limit,@Param("offset") int offset);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket ORDER BY created_at DESC LIMIT #{limit} OFFSET #{offset}") List<TicketView> listAll(@Param("limit") int limit,@Param("offset") int offset);
 @Insert("INSERT INTO service_ticket(id,ticket_no,customer_id,order_id,order_item_id,requested_type,status,priority,title,description,client_request_id,version,created_at,updated_at) VALUES(#{id},#{ticketNo},#{customerId},#{orderId},#{orderItemId},#{requestedType},#{status},#{priority},#{title},#{description},#{clientRequestId},0,#{now},#{now})") int insertTicket(@Param("id") long id,@Param("ticketNo") String no,@Param("customerId") long customerId,@Param("orderId") long orderId,@Param("orderItemId") long itemId,@Param("requestedType") String type,@Param("status") String status,@Param("priority") String priority,@Param("title") String title,@Param("description") String description,@Param("clientRequestId") String clientRequestId,@Param("now") LocalDateTime now);
 @Insert("INSERT INTO active_ticket_guard(order_item_id,ticket_id,created_at) VALUES(#{itemId},#{ticketId},#{now})") int insertGuard(@Param("itemId") long itemId,@Param("ticketId") long ticketId,@Param("now") LocalDateTime now);
 @Insert("INSERT INTO ticket_timeline(id,ticket_id,event_type,actor_type,actor_id,summary,detail_json,created_at) VALUES(#{id},#{ticketId},#{eventType},#{actorType},#{actorId},#{summary},#{detailJson},#{now})") int insertTimeline(@Param("id") long id,@Param("ticketId") long ticketId,@Param("eventType") String eventType,@Param("actorType") String actorType,@Param("actorId") Long actorId,@Param("summary") String summary,@Param("detailJson") String detailJson,@Param("now") LocalDateTime now);
 @Insert("INSERT INTO ticket_message(id,ticket_id,sender_type,sender_id,visibility,message_type,content,created_at,updated_at) VALUES(#{id},#{ticketId},#{senderType},#{senderId},#{visibility},#{messageType},#{content},#{now},#{now})") int insertMessage(@Param("id") long id,@Param("ticketId") long ticketId,@Param("senderType") String senderType,@Param("senderId") Long senderId,@Param("visibility") String visibility,@Param("messageType") String messageType,@Param("content") String content,@Param("now") LocalDateTime now);
 @Update("UPDATE service_ticket SET version=version+1,updated_at=#{now},first_response_at=CASE WHEN first_response_at IS NULL AND #{senderType}='AGENT' AND #{visibility}='PUBLIC' THEN #{now} ELSE first_response_at END WHERE id=#{id} AND version=#{version}") int touchMessage(@Param("id") long id,@Param("senderType") String senderType,@Param("visibility") String visibility,@Param("version") int version,@Param("now") LocalDateTime now);
 @Select("SELECT id,sender_type senderType,sender_id senderId,visibility,message_type messageType,content,created_at createdAt FROM ticket_message WHERE ticket_id=#{ticketId} AND (visibility='PUBLIC' OR #{internal}=1) ORDER BY created_at ASC") List<MessageView> messages(@Param("ticketId") long ticketId,@Param("internal") int internal);
 @Select("SELECT id,event_type eventType,actor_type actorType,actor_id actorId,summary,detail_json detailJson,created_at createdAt FROM ticket_timeline WHERE ticket_id=#{ticketId} AND (event_type&lt;&gt;'INTERNAL_NOTE' OR #{internal}=1) ORDER BY created_at ASC,id ASC") List<TimelineView> timeline(@Param("ticketId") long ticketId,@Param("internal") int internal);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket WHERE id=#{id} FOR UPDATE") Optional<TicketView> lockView(@Param("id") long id);
 @Update("UPDATE service_ticket SET status=#{status},assigned_agent_id=COALESCE(#{agentId},assigned_agent_id),version=version+1,updated_at=#{now},resolved_at=CASE WHEN #{status}='RESOLVED' THEN #{now} ELSE resolved_at END,closed_at=CASE WHEN #{status}='CLOSED' THEN #{now} ELSE closed_at END WHERE id=#{id} AND version=#{version}") int transition(@Param("id") long id,@Param("status") String status,@Param("agentId") Long agentId,@Param("version") int version,@Param("now") LocalDateTime now);
 @Update("UPDATE service_ticket SET status='PENDING_AGENT',version=version+1,updated_at=#{now} WHERE id=#{id} AND version=#{version} AND status='PENDING_CUSTOMER'") int supplement(@Param("id") long id,@Param("version") int version,@Param("now") LocalDateTime now);
 @Delete("DELETE FROM active_ticket_guard WHERE ticket_id=#{ticketId}") int deleteGuard(@Param("ticketId") long ticketId);
}
