package com.aftersales.copilot.ticket.infrastructure.mapper;
 import com.aftersales.copilot.ticket.infrastructure.po.*; import com.baomidou.mybatisplus.core.mapper.BaseMapper; import org.apache.ibatis.annotations.*; import java.time.LocalDateTime; import java.util.*;
@Mapper public interface TicketMapper extends BaseMapper<ServiceTicketPo> {
 record OrderContext(Long itemId,Long orderId,Long customerId,String orderStatus,String productName) {}
 record TicketView(Long id,String ticketNo,Long customerId,Long orderId,Long orderItemId,String requestedType,String confirmedType,String status,String priority,String title,String description,Long assignedAgentId,LocalDateTime firstResponseAt,LocalDateTime resolvedAt,LocalDateTime closedAt,String resolutionCode,String resolutionNote,Integer version,LocalDateTime createdAt,LocalDateTime updatedAt) {}
 record MessageView(Long id,String senderType,Long senderId,String visibility,String messageType,String content,LocalDateTime createdAt) {}
 record TimelineView(Long id,String eventType,String actorType,Long actorId,String summary,String detailJson,LocalDateTime createdAt) {}
 record WorkbenchSummary(Long pendingAssignment,Long myPendingAgent,Long pendingCustomer,Long waitingReturn,Long overdue) {}
 record AgentCandidate(Long id,Long activeCount,LocalDateTime lastAssignedAt) {}
 record EligibilityItem(Long id,Long orderId,Long skuId,Long productId,String category,String orderStatus,Long paidAmountCent,Long refundedAmountCent,LocalDateTime deliveredAt,LocalDateTime warrantyExpireAt,LocalDateTime createdAt) {}
 record RuleView(Long id,String ruleCode,String name,String scopeType,Long scopeId,Integer refundOnlyDays,Integer returnRefundDays,Integer exchangeDays,Integer repairDays,Boolean requiresUnopened,LocalDateTime effectiveFrom,LocalDateTime effectiveTo,String status,Integer version) {}
 @Select("SELECT oi.id itemId, co.id orderId, co.customer_id customerId, co.status orderStatus, oi.product_name_snapshot productName FROM order_item oi JOIN customer_order co ON co.id=oi.order_id WHERE oi.id=#{itemId} AND co.customer_id=#{customerId} LIMIT 1") Optional<OrderContext> findOrderItemForCustomer(@Param("itemId") long itemId,@Param("customerId") long customerId);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket WHERE id=#{id}") Optional<TicketView> findView(@Param("id") long id);
 @Select("SELECT id FROM service_ticket WHERE customer_id=#{customerId} AND client_request_id=#{clientRequestId} LIMIT 1") Optional<Long> findByClientRequest(@Param("customerId") long customerId,@Param("clientRequestId") String clientRequestId);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket WHERE customer_id=#{userId} ORDER BY created_at DESC LIMIT #{limit} OFFSET #{offset}") List<TicketView> listCustomer(@Param("userId") long userId,@Param("limit") int limit,@Param("offset") int offset);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket WHERE (assigned_agent_id=#{userId} OR (#{queue}=1 AND status='PENDING_ASSIGNMENT')) ORDER BY created_at DESC LIMIT #{limit} OFFSET #{offset}") List<TicketView> listAgent(@Param("userId") long userId,@Param("queue") int queue,@Param("limit") int limit,@Param("offset") int offset);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket ORDER BY created_at DESC LIMIT #{limit} OFFSET #{offset}") List<TicketView> listAll(@Param("limit") int limit,@Param("offset") int offset);
 @Insert("INSERT INTO service_ticket(id,ticket_no,customer_id,order_id,order_item_id,requested_type,status,priority,title,description,client_request_id,version,created_at,updated_at) VALUES(#{id},#{ticketNo},#{customerId},#{orderId},#{orderItemId},#{requestedType},#{status},#{priority},#{title},#{description},#{clientRequestId},0,#{now},#{now})") int insertTicket(@Param("id") long id,@Param("ticketNo") String no,@Param("customerId") long customerId,@Param("orderId") long orderId,@Param("orderItemId") long itemId,@Param("requestedType") String type,@Param("status") String status,@Param("priority") String priority,@Param("title") String title,@Param("description") String description,@Param("clientRequestId") String clientRequestId,@Param("now") LocalDateTime now);
 @Insert("INSERT INTO active_ticket_guard(order_item_id,ticket_id,created_at) VALUES(#{itemId},#{ticketId},#{now})") int insertGuard(@Param("itemId") long itemId,@Param("ticketId") long ticketId,@Param("now") LocalDateTime now);
 @Insert("INSERT INTO ticket_timeline(id,ticket_id,event_type,actor_type,actor_id,summary,detail_json,created_at) VALUES(#{id},#{ticketId},#{eventType},#{actorType},#{actorId},#{summary},#{detailJson},#{now})") int insertTimeline(@Param("id") long id,@Param("ticketId") long ticketId,@Param("eventType") String eventType,@Param("actorType") String actorType,@Param("actorId") Long actorId,@Param("summary") String summary,@Param("detailJson") String detailJson,@Param("now") LocalDateTime now);
 @Insert("INSERT INTO ticket_message(id,ticket_id,sender_type,sender_id,visibility,message_type,content,created_at,updated_at) VALUES(#{id},#{ticketId},#{senderType},#{senderId},#{visibility},#{messageType},#{content},#{now},#{now})") int insertMessage(@Param("id") long id,@Param("ticketId") long ticketId,@Param("senderType") String senderType,@Param("senderId") Long senderId,@Param("visibility") String visibility,@Param("messageType") String messageType,@Param("content") String content,@Param("now") LocalDateTime now);
 @Update("UPDATE service_ticket SET version=version+1,updated_at=#{now},first_response_at=CASE WHEN first_response_at IS NULL AND #{senderType}='AGENT' AND #{visibility}='PUBLIC' THEN #{now} ELSE first_response_at END WHERE id=#{id} AND version=#{version}") int touchMessage(@Param("id") long id,@Param("senderType") String senderType,@Param("visibility") String visibility,@Param("version") int version,@Param("now") LocalDateTime now);
 @Select("SELECT id,sender_type senderType,sender_id senderId,visibility,message_type messageType,content,created_at createdAt FROM ticket_message WHERE ticket_id=#{ticketId} AND (visibility='PUBLIC' OR #{internal}=1) ORDER BY created_at ASC") List<MessageView> messages(@Param("ticketId") long ticketId,@Param("internal") int internal);
 @Select("SELECT id,event_type eventType,actor_type actorType,actor_id actorId,summary,detail_json detailJson,created_at createdAt FROM ticket_timeline WHERE ticket_id=#{ticketId} AND (event_type<>'INTERNAL_NOTE' OR #{internal}=1) ORDER BY created_at ASC,id ASC") List<TimelineView> timeline(@Param("ticketId") long ticketId,@Param("internal") int internal);
 @Select("SELECT oi.id,oi.order_id orderId,oi.sku_id skuId,ps.product_id productId,p.category,co.status orderStatus,oi.paid_amount_cent paidAmountCent,oi.refunded_amount_cent refundedAmountCent,co.delivered_at deliveredAt,oi.warranty_expire_at warrantyExpireAt,oi.created_at createdAt FROM order_item oi JOIN customer_order co ON co.id=oi.order_id JOIN product_sku ps ON ps.id=oi.sku_id JOIN product p ON p.id=ps.product_id WHERE oi.id=#{itemId} AND co.customer_id=#{customerId} LIMIT 1") Optional<EligibilityItem> findEligibilityItem(@Param("itemId") long itemId,@Param("customerId") long customerId);
 @Select("SELECT id,rule_code ruleCode,name,scope_type scopeType,scope_id scopeId,refund_only_days refundOnlyDays,return_refund_days returnRefundDays,exchange_days exchangeDays,repair_days repairDays,requires_unopened requiresUnopened,effective_from effectiveFrom,effective_to effectiveTo,status,version FROM warranty_rule WHERE status='ACTIVE' AND effective_from <= #{now} AND (effective_to IS NULL OR effective_to > #{now}) AND ((scope_type='SKU' AND scope_id=#{skuId}) OR (scope_type='PRODUCT' AND scope_id=#{productId}) OR (scope_type='CATEGORY' AND scope_id IN (SELECT id FROM product WHERE category=#{category})) OR scope_type='GLOBAL') ORDER BY CASE scope_type WHEN 'SKU' THEN 1 WHEN 'PRODUCT' THEN 2 WHEN 'CATEGORY' THEN 3 ELSE 4 END,effective_from DESC LIMIT 1") Optional<RuleView> findRule(@Param("category") String category,@Param("productId") long productId,@Param("skuId") long skuId,@Param("now") LocalDateTime now);
 @Select("SELECT id,rule_code ruleCode,name,scope_type scopeType,scope_id scopeId,refund_only_days refundOnlyDays,return_refund_days returnRefundDays,exchange_days exchangeDays,repair_days repairDays,requires_unopened requiresUnopened,effective_from effectiveFrom,effective_to effectiveTo,status,version FROM warranty_rule ORDER BY created_at DESC") List<RuleView> listRules();
 @Insert("INSERT INTO warranty_rule(id,rule_code,name,scope_type,scope_id,refund_only_days,return_refund_days,exchange_days,repair_days,requires_unopened,effective_from,effective_to,status,version,created_at,updated_at) VALUES(#{id},#{code},#{name},#{scopeType},#{scopeId},#{refundOnlyDays},#{returnRefundDays},#{exchangeDays},#{repairDays},#{requiresUnopened},#{from},#{to},#{status},0,#{now},#{now})") int insertRule(@Param("id") long id,@Param("code") String code,@Param("name") String name,@Param("scopeType") String scopeType,@Param("scopeId") Long scopeId,@Param("refundOnlyDays") int refundOnlyDays,@Param("returnRefundDays") int returnRefundDays,@Param("exchangeDays") int exchangeDays,@Param("repairDays") int repairDays,@Param("requiresUnopened") boolean requiresUnopened,@Param("from") LocalDateTime from,@Param("to") LocalDateTime to,@Param("status") String status,@Param("now") LocalDateTime now);
 @Update("UPDATE warranty_rule SET status=#{status},version=version+1,updated_at=#{now} WHERE id=#{id} AND version=#{version}") int updateRuleStatus(@Param("id") long id,@Param("status") String status,@Param("version") int version,@Param("now") LocalDateTime now);
 @Select("SELECT id,ticket_no ticketNo,customer_id customerId,order_id orderId,order_item_id orderItemId,requested_type requestedType,confirmed_type confirmedType,status,priority,title,description,assigned_agent_id assignedAgentId,first_response_at firstResponseAt,resolved_at resolvedAt,closed_at closedAt,resolution_code resolutionCode,resolution_note resolutionNote,version,created_at createdAt,updated_at updatedAt FROM service_ticket WHERE id=#{id} FOR UPDATE") Optional<TicketView> lockView(@Param("id") long id);
 @Update("UPDATE service_ticket SET status=#{status},assigned_agent_id=COALESCE(#{agentId},assigned_agent_id),version=version+1,updated_at=#{now},resolved_at=CASE WHEN #{status}='RESOLVED' THEN #{now} ELSE resolved_at END,closed_at=CASE WHEN #{status}='CLOSED' THEN #{now} ELSE closed_at END WHERE id=#{id} AND version=#{version}") int transition(@Param("id") long id,@Param("status") String status,@Param("agentId") Long agentId,@Param("version") int version,@Param("now") LocalDateTime now);
 @Update("UPDATE service_ticket SET status='PENDING_AGENT',version=version+1,updated_at=#{now} WHERE id=#{id} AND version=#{version} AND status='PENDING_CUSTOMER'") int supplement(@Param("id") long id,@Param("version") int version,@Param("now") LocalDateTime now);
 @Delete("DELETE FROM active_ticket_guard WHERE ticket_id=#{ticketId}") int deleteGuard(@Param("ticketId") long ticketId);
 @Insert("INSERT INTO ticket_assignment_log(id,ticket_id,from_agent_id,to_agent_id,assign_type,reason,operator_id,created_at) VALUES(#{id},#{ticketId},#{fromAgentId},#{toAgentId},#{type},#{reason},#{operatorId},#{now})") int insertAssignment(@Param("id") long id,@Param("ticketId") long ticketId,@Param("fromAgentId") Long fromAgentId,@Param("toAgentId") Long toAgentId,@Param("type") String type,@Param("reason") String reason,@Param("operatorId") Long operatorId,@Param("now") LocalDateTime now);
 @Select("SELECT u.id,COUNT(t.id) activeCount,u.last_assigned_at lastAssignedAt FROM sys_user u LEFT JOIN service_ticket t ON t.assigned_agent_id=u.id AND t.status IN ('PENDING_AGENT','PENDING_CUSTOMER','WAITING_RETURN','RETURN_IN_TRANSIT','RETURN_RECEIVED','PROCESSING') WHERE u.role='AGENT' AND u.status='ACTIVE' AND u.agent_online=1 GROUP BY u.id,u.last_assigned_at ORDER BY activeCount ASC,lastAssignedAt IS NOT NULL,lastAssignedAt ASC,u.id ASC LIMIT 1") Optional<AgentCandidate> findAutoAgent();
 @Update("UPDATE service_ticket SET assigned_agent_id=#{agentId},status='PENDING_AGENT',version=version+1,updated_at=#{now} WHERE id=#{id} AND status='PENDING_ASSIGNMENT' AND assigned_agent_id IS NULL AND version=#{version}") int assignIfUnassigned(@Param("id") long id,@Param("agentId") long agentId,@Param("version") int version,@Param("now") LocalDateTime now);
 @Update("UPDATE service_ticket SET assigned_agent_id=#{agentId},version=version+1,updated_at=#{now} WHERE id=#{id} AND version=#{version}") int transfer(@Param("id") long id,@Param("agentId") long agentId,@Param("version") int version,@Param("now") LocalDateTime now);
 @Update("UPDATE sys_user SET last_assigned_at=#{now},updated_at=#{now} WHERE id=#{agentId}") int touchAgent(@Param("agentId") long agentId,@Param("now") LocalDateTime now);
 @Select("SELECT SUM(status='PENDING_ASSIGNMENT'),SUM(status='PENDING_AGENT' AND assigned_agent_id=#{agentId}),SUM(status='PENDING_CUSTOMER'),SUM(status IN ('WAITING_RETURN','RETURN_IN_TRANSIT','RETURN_RECEIVED')),SUM(status NOT IN ('RESOLVED','REJECTED','CANCELLED','CLOSED') AND updated_at < DATE_SUB(UTC_TIMESTAMP(), INTERVAL 48 HOUR)) FROM service_ticket") WorkbenchSummary summary(@Param("agentId") long agentId);
}
