package com.aftersales.copilot.ticket.application;
import com.aftersales.copilot.auth.domain.*; import com.aftersales.copilot.ticket.api.TicketRequests; import com.aftersales.copilot.ticket.domain.*; import com.aftersales.copilot.ticket.infrastructure.mapper.TicketMapper; import com.aftersales.copilot.auth.infrastructure.SnowflakeIdGenerator; import org.springframework.dao.DuplicateKeyException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class TicketApplicationService {
 private final TicketMapper mapper; private final SnowflakeIdGenerator ids; private final TicketStateMachine stateMachine; public TicketApplicationService(TicketMapper mapper,SnowflakeIdGenerator ids,TicketStateMachine stateMachine){this.mapper=mapper;this.ids=ids;this.stateMachine=stateMachine;}
 @Transactional public Object create(AuthenticatedUser u,TicketRequests.Create r){if(u.role()!=UserRole.CUSTOMER) throw new TicketException("TICKET_CUSTOMER_ONLY","仅消费者可创建工单",org.springframework.http.HttpStatus.FORBIDDEN); if(r.clientRequestId()!=null&&!r.clientRequestId().isBlank()){var previous=mapper.findByClientRequest(u.id(),r.clientRequestId());if(previous.isPresent())return detail(u,previous.get());} var ctx=mapper.findOrderItemForCustomer(r.orderItemId(),u.id()).orElseThrow(()->new TicketException("ORDER_NOT_OWNED","订单不属于当前用户或订单项不存在",org.springframework.http.HttpStatus.FORBIDDEN)); if(!ctx.orderStatus().equals("DELIVERED")) throw new TicketException("AFTER_SALES_NOT_ELIGIBLE","仅已签收订单支持售后",org.springframework.http.HttpStatus.UNPROCESSABLE_ENTITY); long id=ids.nextId(); LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC); String no="AS"+now.toLocalDate().toString().replace("-","")+String.format("%06d",Math.floorMod(id,1000000)); try{mapper.insertTicket(id,no,u.id(),ctx.orderId(),ctx.itemId(),r.requestedType(),"SUBMITTED","MEDIUM",r.title(),r.description(),r.clientRequestId(),now); mapper.insertGuard(ctx.itemId(),id,now);}catch(DuplicateKeyException e){if(r.clientRequestId()!=null&&!r.clientRequestId().isBlank())return detail(u,mapper.findByClientRequest(u.id(),r.clientRequestId()).orElseThrow());throw TicketException.activeExists();} mapper.insertTimeline(ids.nextId(),id,"SUBMITTED","CUSTOMER",u.id(),"用户提交工单",null,now); mapper.transition(id,"PENDING_ASSIGNMENT",null,0,now); mapper.insertTimeline(ids.nextId(),id,"PENDING_ASSIGNMENT","SYSTEM",null,"工单进入客服队列",null,now); return detail(u,id);}
 public Object list(AuthenticatedUser u,int page,int size){int off=(page-1)*size; if(u.role()==UserRole.CUSTOMER)return mapper.listCustomer(u.id(),size,off); if(u.role()==UserRole.ADMIN)return mapper.listAll(size,off); return mapper.listAgent(u.id(),1,size,off);}
 public Object detail(AuthenticatedUser u,long id){var t=mapper.findView(id).orElseThrow(TicketException::notFound); checkAccess(u,t); return new TicketDetail(t,actions(u,t),mapper.messages(id,u.role()==UserRole.CUSTOMER?0:1));}
 public Object timeline(AuthenticatedUser u,long id){var t=mapper.findView(id).orElseThrow(TicketException::notFound);checkAccess(u,t);return mapper.timeline(id,u.role()==UserRole.CUSTOMER?0:1);}
 @Transactional public Object message(AuthenticatedUser u,long id,TicketRequests.Message r){var t=mapper.lockView(id).orElseThrow(TicketException::notFound);checkAccess(u,t); boolean agent=u.role()!=UserRole.CUSTOMER; String vis=r.visibility().toUpperCase(Locale.ROOT); String type=r.messageType()==null?"TEXT":r.messageType().toUpperCase(Locale.ROOT); if(!vis.equals("PUBLIC")&&!vis.equals("INTERNAL")) throw new TicketException("TICKET_MESSAGE_INVALID","消息可见性不合法",org.springframework.http.HttpStatus.BAD_REQUEST); if(!agent&&!vis.equals("PUBLIC")) throw new TicketException("TICKET_INTERNAL_FORBIDDEN","用户只能发送公开消息",org.springframework.http.HttpStatus.FORBIDDEN); if(!agent&&!type.equals("TEXT")) throw new TicketException("TICKET_MESSAGE_INVALID","用户只能发送文本消息",org.springframework.http.HttpStatus.BAD_REQUEST); if(t.version()!=r.version())throw TicketException.version(); LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC); mapper.insertMessage(ids.nextId(),id,agent?"AGENT":"CUSTOMER",u.id(),vis,type,r.content(),now); if(mapper.touchMessage(id,agent?"AGENT":"CUSTOMER",vis,r.version(),now)!=1)throw TicketException.version(); mapper.insertTimeline(ids.nextId(),id,vis.equals("INTERNAL")?"INTERNAL_NOTE":"MESSAGE",agent?"AGENT":"CUSTOMER",u.id(),vis.equals("INTERNAL")?"客服添加内部备注":"发送公开消息",null,now); return detail(u,id);}
 @Transactional public Object transition(AuthenticatedUser u,long id,String target,int version,String action){var t=mapper.lockView(id).orElseThrow(TicketException::notFound);checkAccess(u,t);TicketStatus targetStatus=TicketStatus.valueOf(target);stateMachine.validate(u.role(),TicketStatus.valueOf(t.status()),targetStatus,action);LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);if(mapper.transition(id,target,null,version,now)!=1)throw TicketException.version();if(Set.of(TicketStatus.RESOLVED,TicketStatus.REJECTED,TicketStatus.CANCELLED).contains(targetStatus))mapper.deleteGuard(id);mapper.insertTimeline(ids.nextId(),id,target,u.role()==UserRole.CUSTOMER?"CUSTOMER":"AGENT",u.id(),actionSummary(action),null,now);return detail(u,id);}
 @Transactional public Object claim(AuthenticatedUser u,long id,int version){if(u.role()==UserRole.CUSTOMER)throw new TicketException("TICKET_AGENT_ONLY","仅客服可领取工单",org.springframework.http.HttpStatus.FORBIDDEN);var t=mapper.lockView(id).orElseThrow(TicketException::notFound);if(!t.status().equals("PENDING_ASSIGNMENT")||t.assignedAgentId()!=null)throw TicketException.invalid(t.status(),"CLAIM");LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);if(mapper.transition(id,"PENDING_AGENT",u.id(),version,now)!=1)throw TicketException.version();mapper.insertTimeline(ids.nextId(),id,"CLAIM","AGENT",u.id(),"客服领取工单",null,now);return detail(u,id);}
 @Transactional public Object supplement(AuthenticatedUser u,long id,int version){var t=mapper.lockView(id).orElseThrow(TicketException::notFound);checkAccess(u,t);if(u.role()!=UserRole.CUSTOMER||!t.status().equals("PENDING_CUSTOMER"))throw TicketException.invalid(t.status(),"SUPPLEMENT");LocalDateTime now=LocalDateTime.now(ZoneOffset.UTC);if(mapper.supplement(id,version,now)!=1)throw TicketException.version();mapper.insertTimeline(ids.nextId(),id,"SUPPLEMENT","CUSTOMER",u.id(),"用户补充信息，恢复客服处理",null,now);return detail(u,id);}
 private void checkAccess(AuthenticatedUser u,TicketMapper.TicketView t){if(u.role()==UserRole.CUSTOMER&&t.customerId()!=u.id())throw TicketException.notOwned();if(u.role()==UserRole.AGENT&&t.assignedAgentId()!=null&&t.assignedAgentId()!=u.id())throw new TicketException("TICKET_NOT_ASSIGNED_TO_AGENT","工单不属于当前客服",org.springframework.http.HttpStatus.FORBIDDEN);}
 private List<String> actions(AuthenticatedUser u,TicketMapper.TicketView t){var a=new ArrayList<String>(); if(u.role()==UserRole.CUSTOMER){if(!Set.of("PROCESSING","RESOLVED","REJECTED","CANCELLED","CLOSED").contains(t.status()))a.add("SEND_MESSAGE");if(Set.of("SUBMITTED","PENDING_ASSIGNMENT","PENDING_AGENT","PENDING_CUSTOMER","WAITING_RETURN","RETURN_IN_TRANSIT","RETURN_RECEIVED").contains(t.status()))a.add("CANCEL");if(t.status().equals("PENDING_CUSTOMER"))a.add("SUPPLEMENT");} else {if(Set.of("PENDING_AGENT","PENDING_CUSTOMER").contains(t.status()))a.add("SEND_MESSAGE");if(t.status().equals("PENDING_AGENT"))a.add("REQUEST_INFO");if(Set.of("PENDING_ASSIGNMENT","PENDING_AGENT","PENDING_CUSTOMER").contains(t.status()))a.add("REJECT");if(Set.of("RESOLVED","REJECTED","CANCELLED").contains(t.status()))a.add("CLOSE");} return a;}
 public record TicketDetail(@com.fasterxml.jackson.annotation.JsonUnwrapped TicketMapper.TicketView ticket,List<String> availableActions,List<TicketMapper.MessageView> messages) {}
 private String actionSummary(String a){return switch(a){case "REQUEST_INFO"->"客服请求用户补充信息";case "REJECT"->"客服拒绝工单";case "CANCEL"->"工单已取消";case "CLOSE"->"工单已关闭";default->a;};}
}

