package com.aftersales.copilot.proposal.infrastructure;

import org.apache.ibatis.annotations.*;
import java.time.LocalDateTime;
import java.util.*;

@Mapper
public interface ProposalMapper {
    record TicketContext(Long id, Long customerId, Long assignedAgentId, Long orderItemId, String status, Integer version,
                         Long paidAmountCent, Long refundedAmountCent, String requestedType) {}
    record ProposalView(Long id, String proposalNo, Long ticketId, String type, String source, String status,
                        Long requestedAmountCent, Long refundAmountCent, String reasonCode, String description,
                        String conditions, Long createdBy, Long reviewedBy, LocalDateTime expiresAt,
                        LocalDateTime confirmedAt, LocalDateTime rejectedAt, LocalDateTime executedAt,
                        Integer version, LocalDateTime createdAt, LocalDateTime updatedAt) {}
    record ExecutionView(Long id, Long proposalId, String idempotencyKey, String status, Long executorId,
                         String requestHash, String resultJson, String errorCode, String errorMessage) {}

    @Select("SELECT t.id,t.customer_id customerId,t.assigned_agent_id assignedAgentId,t.order_item_id orderItemId,t.status,t.version,oi.paid_amount_cent paidAmountCent,oi.refunded_amount_cent refundedAmountCent,t.requested_type requestedType FROM service_ticket t JOIN order_item oi ON oi.id=t.order_item_id WHERE t.id=#{id} FOR UPDATE")
    Optional<TicketContext> lockTicket(@Param("id") long id);
    @Select("SELECT id,proposal_no proposalNo,ticket_id ticketId,type,source,status,requested_amount_cent requestedAmountCent,refund_amount_cent refundAmountCent,reason_code reasonCode,description,conditions_json conditions,created_by createdBy,reviewed_by reviewedBy,expires_at expiresAt,confirmed_at confirmedAt,rejected_at rejectedAt,executed_at executedAt,version,created_at createdAt,updated_at updatedAt FROM service_proposal WHERE id=#{id}")
    Optional<ProposalView> findProposal(@Param("id") long id);
    @Select("SELECT id,proposal_no proposalNo,ticket_id ticketId,type,source,status,requested_amount_cent requestedAmountCent,refund_amount_cent refundAmountCent,reason_code reasonCode,description,conditions_json conditions,created_by createdBy,reviewed_by reviewedBy,expires_at expiresAt,confirmed_at confirmedAt,rejected_at rejectedAt,executed_at executedAt,version,created_at createdAt,updated_at updatedAt FROM service_proposal WHERE id=#{id} FOR UPDATE")
    Optional<ProposalView> lockProposal(@Param("id") long id);
    @Select("SELECT id,proposal_no proposalNo,ticket_id ticketId,type,source,status,requested_amount_cent requestedAmountCent,refund_amount_cent refundAmountCent,reason_code reasonCode,description,conditions_json conditions,created_by createdBy,reviewed_by reviewedBy,expires_at expiresAt,confirmed_at confirmedAt,rejected_at rejectedAt,executed_at executedAt,version,created_at createdAt,updated_at updatedAt FROM service_proposal WHERE ticket_id=#{ticketId} ORDER BY created_at DESC")
    List<ProposalView> listByTicket(@Param("ticketId") long ticketId);
    @Select("SELECT id,proposal_no proposalNo,ticket_id ticketId,type,source,status,requested_amount_cent requestedAmountCent,refund_amount_cent refundAmountCent,reason_code reasonCode,description,conditions_json conditions,created_by createdBy,reviewed_by reviewedBy,expires_at expiresAt,confirmed_at confirmedAt,rejected_at rejectedAt,executed_at executedAt,version,created_at createdAt,updated_at updatedAt FROM service_proposal WHERE ticket_id=#{ticketId} AND status='PENDING_CONFIRMATION' LIMIT 1") Optional<ProposalView> findPending(@Param("ticketId") long ticketId);
    @Insert("INSERT INTO service_proposal(id,proposal_no,ticket_id,type,source,status,requested_amount_cent,refund_amount_cent,reason_code,description,conditions_json,created_by,expires_at,version,created_at,updated_at) VALUES(#{id},#{no},#{ticketId},#{type},#{source},'DRAFT',#{requested},#{refund},#{reason},#{description},#{conditions},#{createdBy},#{expiresAt},0,#{now},#{now})") int insertProposal(@Param("id") long id,@Param("no") String no,@Param("ticketId") long ticketId,@Param("type") String type,@Param("source") String source,@Param("requested") long requested,@Param("refund") long refund,@Param("reason") String reason,@Param("description") String description,@Param("conditions") String conditions,@Param("createdBy") long createdBy,@Param("expiresAt") LocalDateTime expiresAt,@Param("now") LocalDateTime now);
    @Update("UPDATE service_proposal SET status='PENDING_CONFIRMATION',reviewed_by=#{reviewedBy},version=version+1,updated_at=#{now} WHERE id=#{id} AND status='DRAFT' AND version=#{version}") int publish(@Param("id") long id,@Param("reviewedBy") long reviewedBy,@Param("version") int version,@Param("now") LocalDateTime now);
    @Update("UPDATE service_proposal SET status='REJECTED',rejected_at=#{now},version=version+1,updated_at=#{now} WHERE id=#{id} AND status='PENDING_CONFIRMATION' AND version=#{version}") int reject(@Param("id") long id,@Param("version") int version,@Param("now") LocalDateTime now);
    @Update("UPDATE service_proposal SET status=#{status},confirmed_at=CASE WHEN #{status}='CONFIRMED' THEN #{now} ELSE confirmed_at END,executed_at=CASE WHEN #{status}='EXECUTED' THEN #{now} ELSE executed_at END,version=version+1,updated_at=#{now} WHERE id=#{id} AND version=#{version}") int updateStatus(@Param("id") long id,@Param("status") String status,@Param("version") int version,@Param("now") LocalDateTime now);
    @Insert("INSERT INTO proposal_execution(id,proposal_id,idempotency_key,status,executor_id,request_hash,created_at,updated_at) VALUES(#{id},#{proposalId},#{key},'PROCESSING',#{executorId},#{hash},#{now},#{now})") int insertExecution(@Param("id") long id,@Param("proposalId") long proposalId,@Param("key") String key,@Param("executorId") long executorId,@Param("hash") String hash,@Param("now") LocalDateTime now);
    @Select("SELECT id,proposal_id proposalId,idempotency_key idempotencyKey,status,executor_id executorId,request_hash requestHash,result_json resultJson,error_code errorCode,error_message errorMessage FROM proposal_execution WHERE idempotency_key=#{key}") Optional<ExecutionView> findExecutionByKey(@Param("key") String key);
    @Select("SELECT id,proposal_id proposalId,idempotency_key idempotencyKey,status,executor_id executorId,request_hash requestHash,result_json resultJson,error_code errorCode,error_message errorMessage FROM proposal_execution WHERE proposal_id=#{proposalId}") Optional<ExecutionView> findExecutionByProposal(@Param("proposalId") long proposalId);
    @Update("UPDATE proposal_execution SET status=#{status},result_json=#{result},error_code=#{errorCode},error_message=#{errorMessage},updated_at=#{now} WHERE id=#{id}") int finishExecution(@Param("id") long id,@Param("status") String status,@Param("result") String result,@Param("errorCode") String errorCode,@Param("errorMessage") String errorMessage,@Param("now") LocalDateTime now);
    @Update("UPDATE service_ticket SET status=#{status},version=version+1,updated_at=#{now},resolved_at=CASE WHEN #{status}='RESOLVED' THEN #{now} ELSE resolved_at END WHERE id=#{id} AND status=#{fromStatus} AND version=#{version}") int transitionTicket(@Param("id") long id,@Param("fromStatus") String fromStatus,@Param("status") String status,@Param("version") int version,@Param("now") LocalDateTime now);
    @Update("UPDATE order_item SET refunded_amount_cent=refunded_amount_cent+#{amount},version=version+1,updated_at=#{now} WHERE id=#{id} AND refunded_amount_cent+#{amount}<=paid_amount_cent") int refundItem(@Param("id") long id,@Param("amount") long amount,@Param("now") LocalDateTime now);
    @Delete("DELETE FROM active_ticket_guard WHERE ticket_id=#{ticketId}") int deleteActiveGuard(@Param("ticketId") long ticketId);
    @Insert("INSERT INTO refund_record(id,refund_no,ticket_id,proposal_id,order_item_id,amount_cent,status,created_at,updated_at) VALUES(#{id},#{no},#{ticketId},#{proposalId},#{itemId},#{amount},'SUCCEEDED',#{now},#{now})") int insertRefund(@Param("id") long id,@Param("no") String no,@Param("ticketId") long ticketId,@Param("proposalId") long proposalId,@Param("itemId") long itemId,@Param("amount") long amount,@Param("now") LocalDateTime now);
    @Insert("INSERT INTO ticket_timeline(id,ticket_id,event_type,actor_type,actor_id,summary,detail_json,created_at) VALUES(#{id},#{ticketId},#{eventType},#{actorType},#{actorId},#{summary},#{detail},#{now})") int insertTimeline(@Param("id") long id,@Param("ticketId") long ticketId,@Param("eventType") String eventType,@Param("actorType") String actorType,@Param("actorId") Long actorId,@Param("summary") String summary,@Param("detail") String detail,@Param("now") LocalDateTime now);
    @Insert("INSERT INTO audit_log(id,trace_id,actor_type,actor_id,action,resource_type,resource_id,result,before_json,after_json,created_at) VALUES(#{id},#{traceId},#{actorType},#{actorId},#{action},#{resourceType},#{resourceId},#{result},#{beforeJson},#{afterJson},#{now})") int insertAudit(@Param("id") long id,@Param("traceId") String traceId,@Param("actorType") String actorType,@Param("actorId") Long actorId,@Param("action") String action,@Param("resourceType") String resourceType,@Param("resourceId") Long resourceId,@Param("result") String result,@Param("beforeJson") String beforeJson,@Param("afterJson") String afterJson,@Param("now") LocalDateTime now);
}
